apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  type: LoadBalancer
  selector:
    app: goviolin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080